name: Build & Release Electron App

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 🛠 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Setup Node.js & Yarn
        uses: actions/setup-node@v3
        with:
          node-version: v20.18.0
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🛠 Install Snapcraft (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install snapcraft --classic

      - name: 🔨 Build Electron App
        run: yarn build

      - name: 📦 Package App
        run: yarn electron-builder --publish=always

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ runner.os }}
          path: dist/

      - name: 🚀 Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          token: ${{ secrets.GH_PAT }}
